=begin
#bLoyal.LoyaltyService

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.29
=end

require 'spec_helper'
require 'json'

# Unit tests for BloyalLoyaltyClient::ClubMembershipApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ClubMembershipApi' do
  before do
    # run before each test
    @instance = BloyalLoyaltyClient::ClubMembershipApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ClubMembershipApi' do
    it 'should create an instance of ClubMembershipApi' do
      expect(@instance).to be_instance_of(BloyalLoyaltyClient::ClubMembershipApi)
    end
  end

  # unit tests for close_club_close_club_async
  # @param body 
  # @param access_key 
  # @param [Hash] opts the optional parameters
  # @return [ServerResponseCommandResponse]
  describe 'close_club_close_club_async test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for close_club_close_club_async
  # @param customer_uid 
  # @param club_uid 
  # @param close_date 
  # @param created 
  # @param created_local 
  # @param transaction_uid 
  # @param transaction_external_id 
  # @param device_uid 
  # @param store_code 
  # @param device_code 
  # @param cashier_uid 
  # @param cashier_code 
  # @param cashier_external_id 
  # @param uid 
  # @param reference_number 
  # @param system_uid 
  # @param connector_uid 
  # @param access_key 
  # @param [Hash] opts the optional parameters
  # @return [ServerResponseCommandResponse]
  describe 'close_club_close_club_async test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for clubs_get_clubs
  # @param access_key 
  # @param [Hash] opts the optional parameters
  # @return [ServerResponseIEnumerableClub]
  describe 'clubs_get_clubs test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for expire_club_expire_club_async
  # @param body 
  # @param access_key 
  # @param [Hash] opts the optional parameters
  # @return [ServerResponseCommandResponse]
  describe 'expire_club_expire_club_async test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for expire_club_expire_club_async
  # @param customer_uid 
  # @param club_uid 
  # @param expiration_date 
  # @param created 
  # @param created_local 
  # @param transaction_uid 
  # @param transaction_external_id 
  # @param device_uid 
  # @param store_code 
  # @param device_code 
  # @param cashier_uid 
  # @param cashier_code 
  # @param cashier_external_id 
  # @param uid 
  # @param reference_number 
  # @param system_uid 
  # @param connector_uid 
  # @param access_key 
  # @param [Hash] opts the optional parameters
  # @return [ServerResponseCommandResponse]
  describe 'expire_club_expire_club_async test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for inactivate_club_membership_inactivate_club_async
  # @param body 
  # @param access_key 
  # @param [Hash] opts the optional parameters
  # @return [ServerResponseCommandResponse]
  describe 'inactivate_club_membership_inactivate_club_async test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for inactivate_club_membership_inactivate_club_async
  # @param membership_uid 
  # @param customer_uid 
  # @param club_uid 
  # @param activation_date 
  # @param enable_loyalty_benefits_while_inactive 
  # @param device_uid 
  # @param store_code 
  # @param device_code 
  # @param cashier_uid 
  # @param cashier_code 
  # @param cashier_external_id 
  # @param uid 
  # @param reference_number 
  # @param system_uid 
  # @param connector_uid 
  # @param access_key 
  # @param [Hash] opts the optional parameters
  # @return [ServerResponseCommandResponse]
  describe 'inactivate_club_membership_inactivate_club_async test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for join_club_join_club_async
  # @param body 
  # @param access_key 
  # @param [Hash] opts the optional parameters
  # @return [ServerResponseCommandResponse]
  describe 'join_club_join_club_async test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for join_club_join_club_async
  # @param customer_uid 
  # @param club_uid 
  # @param start_date 
  # @param expiration_date 
  # @param created 
  # @param created_local 
  # @param sponsor_uid 
  # @param referral_uid 
  # @param transaction_uid 
  # @param transaction_external_id 
  # @param fulfillment 
  # @param payment 
  # @param auto_billing_day 
  # @param auto_billing_start_date 
  # @param member_comment 
  # @param product_preference_type 
  # @param product_preferences 
  # @param custom_fields 
  # @param device_uid 
  # @param store_code 
  # @param device_code 
  # @param cashier_uid 
  # @param cashier_code 
  # @param cashier_external_id 
  # @param uid 
  # @param reference_number 
  # @param system_uid 
  # @param connector_uid 
  # @param access_key 
  # @param [Hash] opts the optional parameters
  # @return [ServerResponseCommandResponse]
  describe 'join_club_join_club_async test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for query_club_memberships_get_club_memberships_async
  # @param access_key 
  # @param [Hash] opts the optional parameters
  # @return [ServerResponseIEnumerableClubMembership]
  describe 'query_club_memberships_get_club_memberships_async test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for renew_club_membership_renew_club_async
  # @param body 
  # @param access_key 
  # @param [Hash] opts the optional parameters
  # @return [ServerResponseCommandResponse]
  describe 'renew_club_membership_renew_club_async test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for renew_club_membership_renew_club_async
  # @param membership_uid 
  # @param customer_uid 
  # @param club_uid 
  # @param expiration_date 
  # @param transaction_uid 
  # @param transaction_external_id 
  # @param referral_uid 
  # @param sponsor_uid 
  # @param fulfillment 
  # @param payment 
  # @param auto_billing_day 
  # @param auto_billing_start_date 
  # @param member_comment 
  # @param product_preference_type 
  # @param product_preferences 
  # @param device_uid 
  # @param store_code 
  # @param device_code 
  # @param cashier_uid 
  # @param cashier_code 
  # @param cashier_external_id 
  # @param uid 
  # @param reference_number 
  # @param system_uid 
  # @param connector_uid 
  # @param access_key 
  # @param [Hash] opts the optional parameters
  # @return [ServerResponseCommandResponse]
  describe 'renew_club_membership_renew_club_async test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for reverse_club_membership_reverse_club_membeship_async
  # @param body 
  # @param access_key 
  # @param [Hash] opts the optional parameters
  # @return [ServerResponseCommandResponse]
  describe 'reverse_club_membership_reverse_club_membeship_async test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for reverse_club_membership_reverse_club_membeship_async
  # @param uid 
  # @param reference_number 
  # @param command_uid 
  # @param access_key 
  # @param [Hash] opts the optional parameters
  # @return [ServerResponseCommandResponse]
  describe 'reverse_club_membership_reverse_club_membeship_async test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for void_club_membership_void_loyalty_points_async
  # @param body 
  # @param access_key 
  # @param [Hash] opts the optional parameters
  # @return [ServerResponseCommandResponse]
  describe 'void_club_membership_void_loyalty_points_async test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for void_club_membership_void_loyalty_points_async
  # @param uid 
  # @param reference_number 
  # @param transaction_uid 
  # @param access_key 
  # @param [Hash] opts the optional parameters
  # @return [ServerResponseCommandResponse]
  describe 'void_club_membership_void_loyalty_points_async test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
