=begin
#bLoyal.LoyaltyService

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.29
=end

require 'spec_helper'
require 'json'

# Unit tests for BloyalLoyaltyClient::DeviceScopedSnippetConfigApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DeviceScopedSnippetConfigApi' do
  before do
    # run before each test
    @instance = BloyalLoyaltyClient::DeviceScopedSnippetConfigApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DeviceScopedSnippetConfigApi' do
    it 'should create an instance of DeviceScopedSnippetConfigApi' do
      expect(@instance).to be_instance_of(BloyalLoyaltyClient::DeviceScopedSnippetConfigApi)
    end
  end

  # unit tests for query_scoped_web_snippet_profile_get_async
  # @param login_domain 
  # @param device_code 
  # @param uid 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :code 
  # @option opts [BOOLEAN] :check_legacy 
  # @return [ServerResponseWebSnippetProfile]
  describe 'query_scoped_web_snippet_profile_get_async test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for query_scoped_web_snippet_profile_summaries_get_async
  # @param login_domain 
  # @param device_code 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :type 
  # @return [ServerResponseWebSnippetProfileSummary]
  describe 'query_scoped_web_snippet_profile_summaries_get_async test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
