=begin
#bLoyal.LoyaltyService

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.29
=end

require 'spec_helper'
require 'json'

# Unit tests for BloyalLoyaltyClient::SnippetsEngagementsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SnippetsEngagementsApi' do
  before do
    # run before each test
    @instance = BloyalLoyaltyClient::SnippetsEngagementsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SnippetsEngagementsApi' do
    it 'should create an instance of SnippetsEngagementsApi' do
      expect(@instance).to be_instance_of(BloyalLoyaltyClient::SnippetsEngagementsApi)
    end
  end

  # unit tests for record_engagement_token_scoped_get_async
  # @param body 
  # @param login_domain 
  # @param device_code 
  # @param [Hash] opts the optional parameters
  # @return [ServerResponseEngagementTransaction]
  describe 'record_engagement_token_scoped_get_async test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for record_engagement_token_scoped_get_async
  # @param engagement_token 
  # @param quantity 
  # @param message 
  # @param device_uid 
  # @param store_code 
  # @param device_code2 
  # @param cashier_uid 
  # @param cashier_code 
  # @param cashier_external_id 
  # @param uid 
  # @param reference_number 
  # @param system_uid 
  # @param connector_uid 
  # @param login_domain 
  # @param device_code 
  # @param [Hash] opts the optional parameters
  # @return [ServerResponseEngagementTransaction]
  describe 'record_engagement_token_scoped_get_async test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
