=begin
#bLoyal.LoyaltyService

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.29
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BloyalLoyaltyClient::CommandResponse
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CommandResponse' do
  before do
    # run before each test
    @instance = BloyalLoyaltyClient::CommandResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CommandResponse' do
    it 'should create an instance of CommandResponse' do
      expect(@instance).to be_instance_of(BloyalLoyaltyClient::CommandResponse)
    end
  end
  describe 'test attribute "command_uid"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "receipt_message"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
