=begin
#bLoyal.LoyaltyService

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.29
=end

require 'date'

module BloyalLoyaltyClient
  class WebSnippetProfileSummary
    attr_accessor :uid

    attr_accessor :revision

    attr_accessor :external_id

    attr_accessor :code

    attr_accessor :name

    attr_accessor :is_valid

    attr_accessor :type

    attr_accessor :theme

    attr_accessor :title

    attr_accessor :message

    attr_accessor :on_success_redirect_url

    attr_accessor :on_success_message

    attr_accessor :on_success_redirect_delay

    attr_accessor :login_type

    attr_accessor :login_snippet_code

    attr_accessor :login_url

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'uid' => :'Uid',
        :'revision' => :'Revision',
        :'external_id' => :'ExternalId',
        :'code' => :'Code',
        :'name' => :'Name',
        :'is_valid' => :'IsValid',
        :'type' => :'Type',
        :'theme' => :'Theme',
        :'title' => :'Title',
        :'message' => :'Message',
        :'on_success_redirect_url' => :'OnSuccessRedirectUrl',
        :'on_success_message' => :'OnSuccessMessage',
        :'on_success_redirect_delay' => :'OnSuccessRedirectDelay',
        :'login_type' => :'LoginType',
        :'login_snippet_code' => :'LoginSnippetCode',
        :'login_url' => :'LoginUrl'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'uid' => :'Object',
        :'revision' => :'Object',
        :'external_id' => :'Object',
        :'code' => :'Object',
        :'name' => :'Object',
        :'is_valid' => :'Object',
        :'type' => :'Object',
        :'theme' => :'Object',
        :'title' => :'Object',
        :'message' => :'Object',
        :'on_success_redirect_url' => :'Object',
        :'on_success_message' => :'Object',
        :'on_success_redirect_delay' => :'Object',
        :'login_type' => :'Object',
        :'login_snippet_code' => :'Object',
        :'login_url' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end
  
    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `BloyalLoyaltyClient::WebSnippetProfileSummary` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `BloyalLoyaltyClient::WebSnippetProfileSummary`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'uid')
        self.uid = attributes[:'uid']
      end

      if attributes.key?(:'revision')
        self.revision = attributes[:'revision']
      end

      if attributes.key?(:'external_id')
        self.external_id = attributes[:'external_id']
      end

      if attributes.key?(:'code')
        self.code = attributes[:'code']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'is_valid')
        self.is_valid = attributes[:'is_valid']
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.key?(:'theme')
        self.theme = attributes[:'theme']
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      end

      if attributes.key?(:'message')
        self.message = attributes[:'message']
      end

      if attributes.key?(:'on_success_redirect_url')
        self.on_success_redirect_url = attributes[:'on_success_redirect_url']
      end

      if attributes.key?(:'on_success_message')
        self.on_success_message = attributes[:'on_success_message']
      end

      if attributes.key?(:'on_success_redirect_delay')
        self.on_success_redirect_delay = attributes[:'on_success_redirect_delay']
      end

      if attributes.key?(:'login_type')
        self.login_type = attributes[:'login_type']
      end

      if attributes.key?(:'login_snippet_code')
        self.login_snippet_code = attributes[:'login_snippet_code']
      end

      if attributes.key?(:'login_url')
        self.login_url = attributes[:'login_url']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      type_validator = EnumAttributeValidator.new('Object', ['Undefined', 'Login', 'Signup', 'AccountManagement', 'ClubSignup', 'Dashboard', 'CustomerDetails', 'OrderPickup', 'SalesTransactions', 'CustomerReferrals', 'Alert', 'PurchaseHistory', 'PaymentMethods', 'RecordEngagement'])
      return false unless type_validator.valid?(@type)
      theme_validator = EnumAttributeValidator.new('Object', ['Default', 'MaterialUI'])
      return false unless theme_validator.valid?(@theme)
      login_type_validator = EnumAttributeValidator.new('Object', ['Undefined', 'NotRequired', 'ConfiguredUrl', 'ConfiguredSnippet', 'ExternalQueryUrl', 'ExternalQuerySnippet', 'ExternalElementUrl', 'ExternalElementSnippet'])
      return false unless login_type_validator.valid?(@login_type)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] type Object to be assigned
    def type=(type)
      validator = EnumAttributeValidator.new('Object', ['Undefined', 'Login', 'Signup', 'AccountManagement', 'ClubSignup', 'Dashboard', 'CustomerDetails', 'OrderPickup', 'SalesTransactions', 'CustomerReferrals', 'Alert', 'PurchaseHistory', 'PaymentMethods', 'RecordEngagement'])
      unless validator.valid?(type)
        fail ArgumentError, "invalid value for \"type\", must be one of #{validator.allowable_values}."
      end
      @type = type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] theme Object to be assigned
    def theme=(theme)
      validator = EnumAttributeValidator.new('Object', ['Default', 'MaterialUI'])
      unless validator.valid?(theme)
        fail ArgumentError, "invalid value for \"theme\", must be one of #{validator.allowable_values}."
      end
      @theme = theme
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] login_type Object to be assigned
    def login_type=(login_type)
      validator = EnumAttributeValidator.new('Object', ['Undefined', 'NotRequired', 'ConfiguredUrl', 'ConfiguredSnippet', 'ExternalQueryUrl', 'ExternalQuerySnippet', 'ExternalElementUrl', 'ExternalElementSnippet'])
      unless validator.valid?(login_type)
        fail ArgumentError, "invalid value for \"login_type\", must be one of #{validator.allowable_values}."
      end
      @login_type = login_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          uid == o.uid &&
          revision == o.revision &&
          external_id == o.external_id &&
          code == o.code &&
          name == o.name &&
          is_valid == o.is_valid &&
          type == o.type &&
          theme == o.theme &&
          title == o.title &&
          message == o.message &&
          on_success_redirect_url == o.on_success_redirect_url &&
          on_success_message == o.on_success_message &&
          on_success_redirect_delay == o.on_success_redirect_delay &&
          login_type == o.login_type &&
          login_snippet_code == o.login_snippet_code &&
          login_url == o.login_url
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [uid, revision, external_id, code, name, is_valid, type, theme, title, message, on_success_redirect_url, on_success_message, on_success_redirect_delay, login_type, login_snippet_code, login_url].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        elsif attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        BloyalLoyaltyClient.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end  end
end
